name: crust_dart
description: Dart bindings for crust.
version: 0.1.0
homepage: https://github.com/bourdenas/crust_dart

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  path:
  ffi:
  protobuf:

dev_dependencies:
  lints: ^1.0.0
